using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Rpom.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddModulePageAuthorization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent — safe to run on DBs that already have these tables
            // (e.g. after merge + snapshot regeneration).
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS public.modules (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    code character varying(50) NOT NULL,
                    name character varying(200) NOT NULL,
                    display_order smallint NOT NULL DEFAULT 0,
                    CONSTRAINT pk_modules PRIMARY KEY (id)
                );
            """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS ix_modules_code ON public.modules (code);
            """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS public.pages (
                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    code character varying(100) NOT NULL,
                    name character varying(200) NOT NULL,
                    module_id integer NOT NULL,
                    display_order smallint NOT NULL DEFAULT 0,
                    CONSTRAINT pk_pages PRIMARY KEY (id),
                    CONSTRAINT fk_pages_modules_module_id FOREIGN KEY (module_id)
                        REFERENCES public.modules (id) ON DELETE CASCADE
                );
            """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS ix_pages_code ON public.pages (code);
            """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS ix_pages_module_id ON public.pages (module_id);
            """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS public.staff_account_page_accesses (
                    staff_account_id integer NOT NULL,
                    page_id integer NOT NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT pk_staff_account_page_accesses
                        PRIMARY KEY (staff_account_id, page_id),
                    CONSTRAINT fk_staff_account_page_accesses_pages_page_id
                        FOREIGN KEY (page_id) REFERENCES public.pages (id) ON DELETE CASCADE,
                    CONSTRAINT fk_staff_account_page_accesses_staff_accounts_staff_account_id
                        FOREIGN KEY (staff_account_id) REFERENCES public.staff_accounts (id) ON DELETE CASCADE
                );
            """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS ix_staff_account_page_access_page_id
                    ON public.staff_account_page_accesses (page_id);
            """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.staff_account_page_accesses");
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.pages");
            migrationBuilder.Sql("DROP TABLE IF EXISTS public.modules");
        }
    }
}
